### ISSUE TITLE
exe files isnt there

### ISSUE THREAD

**Issue by vqcate** [reverse2222/Hazard-Token-Grabber-v2#18]
hey idk if ur still active on this repo but i did everything succesfully but i cant seem to find the exe file

**Comment by Gumbobrot** [comment]
Yeah, this is a pretty outdated repo and I don't got much time rn to fix the issues.

**So I would suggest you to use this Stealer: It's way better and gets updates frequently**. Also it's developed by me and a friend.
https://github.com/DamagingRose/Rose-Injector

**Comment by vqcate** [comment]
hey is there a tut on how to use it step by step?

**Comment by Gumbobrot** [comment]
> hey is there a tut on how to use it step by step?
> 

Simply check out the setup tab on Rose's Readme.
